version: '3'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_DB: 'testdb'
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      PGDATA: /data/postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres:/data/postgres
    networks:
      - postgres
    restart: always

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-root}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - '${PGADMIN_PORT:-5050}:80'
    networks:
      - postgres
    restart: unless-stopped

  server:
    container_name: server_app_container
    build:
      context: ./server
    environment:
      PORT: 5000
      DB_NAME: testdb
      DB_USER: postgres
      DB_PASSWORD: root
      DB_HOST: host.docker.internal
      DB_PORT: 5432
      SECRET_KEY: TEST_KEY_TEST
    depends_on:
      - postgres
    ports:
      - '5000:5000'

  client:
    container_name: client_app_container
    build:
      context: ./client
    environment:
      REACT_APP_API_URL: http://localhost:5000/
      REACT_APP_MAP_KEY: d4ae80c7-3884-4efc-9823-3e9bfc4f62b3
    depends_on:
      - server
    ports:
      - '3000:3000'
    restart: always

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin:
